import joblib
import os
import pandas as pd
import numpy as np

class UpliftBiddingAgent:
    def __init__(self, model_dir, conversion_value=50.0):
        """
        Initializes the agent with calibrated models and business logic.
        :param conversion_value: The profit generated by one conversion (e.g., $50).
        """
        print("Initializing Causal Bidding Agent")
        self.model_t = joblib.load(os.path.join(model_dir, "t_learner_treatment.joblib"))
        self.model_c = joblib.load(os.path.join(model_dir, "t_learner_control.joblib"))
        self.conversion_value = conversion_value
        
    def calculate_bid(self, user_features):
        """
        Calculates a real-time bid based on predicted incremental lift.
        """
        p_t = self.model_t.predict_proba(user_features)[:, 1]
        p_c = self.model_c.predict_proba(user_features)[:, 1]
        
        uplift = p_t - p_c
        
        # Bid = Uplift * Value. If uplift is negative, bid $0.
        raw_bid = uplift * self.conversion_value
        final_bid = np.maximum(0, raw_bid)
        
        return final_bid, uplift

if __name__ == "__main__":
    MODEL_PATH = "/accounts/masters/quannm/uplift_project/models/v2"
    DATA_PATH = "/accounts/masters/quannm/uplift_project/data/v2_engineered/test_data"
    
    from datasets import load_from_disk
    test_df = load_from_disk(DATA_PATH).to_pandas().sample(5)
    features = [f'f{i}' for i in range(12)] + \
               ['user_freq', 'f3_sq', 'f8_sq', 'f6_sq', 'f3_f6_inter', 'f2_f9_inter']

    agent = UpliftBiddingAgent(MODEL_PATH, conversion_value=100.0)
    
    print("\n--- Real-Time Bidding Simulation ---")
    for i, row in test_df.iterrows():
        user_data = row[features].values.reshape(1, -1)
        bid, lift = agent.calculate_bid(pd.DataFrame(user_data, columns=features))
        
        print(f"User {i}: Predicted Uplift = {lift[0]:.6f} | Recommended Bid = ${bid[0]:.4f}")